# Generated by Django 5.0.3 on 2024-03-29 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_hired', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
