# Generated by Django 5.0.3 on 2024-03-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
