# Generated by Django 5.0.3 on 2024-03-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_emp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
