# Generated by Django 5.0.3 on 2024-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
    ]
