# Generated by Django 5.0.3 on 2024-04-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_remove_task_assignee_task_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleblowingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Open', 'Open'), ('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='whistleblowing_attachments/')),
                ('decision_description', models.TextField(blank=True, null=True)),
                ('involved_employees', models.ManyToManyField(related_name='whistleblowing_cases', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='emp.whistleblowingcase')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Percentage of task responsibility')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.task')),
            ],
            options={
                'unique_together': {('task', 'emp')},
            },
        ),
    ]
