# Generated by Django 5.0.3 on 2024-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_whistleblowingcase_caseconversation_taskassignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
