# Generated by Django 4.1 on 2024-04-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0014_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
    ]
