# Generated by Django 4.1 on 2024-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_remove_task_assignees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('employees', models.ManyToManyField(to='emp.emp')),
                ('tasks', models.ManyToManyField(to='emp.task')),
            ],
        ),
    ]
